export const LITHOLOGIES_IMAGES = [
	{key: 601, uri: require("../assets/lithologies/601.jpg")}, 
	{key: 602, uri: require("../assets/lithologies/602.jpg")},
	{key: 603, uri: require("../assets/lithologies/603.jpg")},
	{key: 605, uri: require("../assets/lithologies/605.jpg")},
	{key: 606, uri: require("../assets/lithologies/606.jpg")},
	{key: 607, uri: require("../assets/lithologies/607.jpg")},
	{key: 608, uri: require("../assets/lithologies/608.jpg")},
	{key: 609, uri: require("../assets/lithologies/609.jpg")},
	{key: 610, uri: require("../assets/lithologies/610.jpg")},
	{key: 611, uri: require("../assets/lithologies/611.jpg")},
	{key: 612, uri: require("../assets/lithologies/612.jpg")},
	{key: 613, uri: require("../assets/lithologies/613.jpg")},
	{key: 614, uri: require("../assets/lithologies/614.jpg")},
	{key: 616, uri: require("../assets/lithologies/616.jpg")},
	{key: 617, uri: require("../assets/lithologies/617.jpg")},
	{key: 618, uri: require("../assets/lithologies/618.jpg")},
	{key: 619, uri: require("../assets/lithologies/619.jpg")},
	{key: 620, uri: require("../assets/lithologies/620.jpg")},
	{key: 621, uri: require("../assets/lithologies/621.jpg")},
	{key: 622, uri: require("../assets/lithologies/622.jpg")},
	{key: 623, uri: require("../assets/lithologies/623.jpg")},
	{key: 624, uri: require("../assets/lithologies/624.jpg")},
	{key: 625, uri: require("../assets/lithologies/625.jpg")},
	{key: 626, uri: require("../assets/lithologies/626.jpg")},
	{key: 627, uri: require("../assets/lithologies/627.jpg")},
	{key: 628, uri: require("../assets/lithologies/628.jpg")},
	{key: 629, uri: require("../assets/lithologies/629.jpg")},
	{key: 630, uri: require("../assets/lithologies/630.jpg")},
	{key: 631, uri: require("../assets/lithologies/631.jpg")},
	{key: 632, uri: require("../assets/lithologies/632.jpg")},
	{key: 633, uri: require("../assets/lithologies/633.jpg")},
	{key: 634, uri: require("../assets/lithologies/634.jpg")},
	{key: 635, uri: require("../assets/lithologies/635.jpg")},
	{key: 636, uri: require("../assets/lithologies/636.jpg")},
	{key: 637, uri: require("../assets/lithologies/637.jpg")},
	{key: 638, uri: require("../assets/lithologies/638.jpg")},
	{key: 639, uri: require("../assets/lithologies/639.jpg")},
	{key: 640, uri: require("../assets/lithologies/640.jpg")},
	{key: 641, uri: require("../assets/lithologies/641.jpg")},
	{key: 642, uri: require("../assets/lithologies/642.jpg")},
	{key: 643, uri: require("../assets/lithologies/643.jpg")},
	{key: 644, uri: require("../assets/lithologies/644.jpg")},
	{key: 645, uri: require("../assets/lithologies/645.jpg")},
	{key: 646, uri: require("../assets/lithologies/646.jpg")},
	{key: 647, uri: require("../assets/lithologies/647.jpg")},
	{key: 648, uri: require("../assets/lithologies/648.jpg")},
	{key: 649, uri: require("../assets/lithologies/649.jpg")},
	{key: 650, uri: require("../assets/lithologies/650.jpg")},
	{key: 651, uri: require("../assets/lithologies/651.jpg")},
	{key: 652, uri: require("../assets/lithologies/652.jpg")},
	{key: 653, uri: require("../assets/lithologies/653.jpg")},
	{key: 654, uri: require("../assets/lithologies/654.jpg")},
	{key: 655, uri: require("../assets/lithologies/655.jpg")},
	{key: 656, uri: require("../assets/lithologies/656.jpg")},
	{key: 657, uri: require("../assets/lithologies/657.jpg")},
	{key: 658, uri: require("../assets/lithologies/658.jpg")},
	{key: 659, uri: require("../assets/lithologies/659.jpg")},
	{key: 660, uri: require("../assets/lithologies/660.jpg")},
	{key: 661, uri: require("../assets/lithologies/661.jpg")},
	{key: 662, uri: require("../assets/lithologies/662.jpg")},
	{key: 663, uri: require("../assets/lithologies/663.jpg")},
	{key: 664, uri: require("../assets/lithologies/664.jpg")},
	{key: 665, uri: require("../assets/lithologies/665.jpg")},
	{key: 666, uri: require("../assets/lithologies/666.jpg")},
	{key: 667, uri: require("../assets/lithologies/667.jpg")},
	{key: 668, uri: require("../assets/lithologies/668.jpg")},
	{key: 669, uri: require("../assets/lithologies/669.jpg")},
	{key: 670, uri: require("../assets/lithologies/670.jpg")},
	{key: 671, uri: require("../assets/lithologies/671.jpg")},
	{key: 672, uri: require("../assets/lithologies/672.jpg")},
	{key: 673, uri: require("../assets/lithologies/673.jpg")},
	{key: 674, uri: require("../assets/lithologies/674.jpg")},
	{key: 675, uri: require("../assets/lithologies/675.jpg")},
	{key: 676, uri: require("../assets/lithologies/676.jpg")},
	{key: 677, uri: require("../assets/lithologies/677.jpg")},
	{key: 678, uri: require("../assets/lithologies/678.jpg")},
	{key: 679, uri: require("../assets/lithologies/679.jpg")},
	{key: 680, uri: require("../assets/lithologies/680.jpg")},
	{key: 681, uri: require("../assets/lithologies/681.jpg")},
	{key: 682, uri: require("../assets/lithologies/682.jpg")},
	{key: 683, uri: require("../assets/lithologies/683.jpg")},
	{key: 684, uri: require("../assets/lithologies/684.jpg")},
	{key: 685, uri: require("../assets/lithologies/685.jpg")},
	{key: 686, uri: require("../assets/lithologies/686.jpg")},
	{key: 701, uri: require("../assets/lithologies/701.jpg")},
	{key: 702, uri: require("../assets/lithologies/702.jpg")},
	{key: 703, uri: require("../assets/lithologies/703.jpg")},
	{key: 704, uri: require("../assets/lithologies/704.jpg")},
	{key: 705, uri: require("../assets/lithologies/705.jpg")},
	{key: 706, uri: require("../assets/lithologies/706.jpg")},
	{key: 707, uri: require("../assets/lithologies/707.jpg")},
	{key: 708, uri: require("../assets/lithologies/708.jpg")},
	{key: 709, uri: require("../assets/lithologies/709.jpg")},
	{key: 710, uri: require("../assets/lithologies/710.jpg")},
	{key: 711, uri: require("../assets/lithologies/711.jpg")},
	{key: 712, uri: require("../assets/lithologies/712.jpg")},
	{key: 713, uri: require("../assets/lithologies/713.jpg")},
	{key: 714, uri: require("../assets/lithologies/714.jpg")},
	{key: 715, uri: require("../assets/lithologies/715.jpg")},
	{key: 716, uri: require("../assets/lithologies/716.jpg")},
	{key: 717, uri: require("../assets/lithologies/717.jpg")},
	{key: 718, uri: require("../assets/lithologies/718.jpg")},
	{key: 719, uri: require("../assets/lithologies/719.jpg")},
	{key: 720, uri: require("../assets/lithologies/720.jpg")},
	{key: 721, uri: require("../assets/lithologies/721.jpg")},
	{key: 722, uri: require("../assets/lithologies/722.jpg")},
	{key: 723, uri: require("../assets/lithologies/723.jpg")},
	{key: 724, uri: require("../assets/lithologies/724.jpg")},
	{key: 725, uri: require("../assets/lithologies/725.jpg")},
	{key: 726, uri: require("../assets/lithologies/726.jpg")},
	{key: 727, uri: require("../assets/lithologies/727.jpg")},
	{key: 728, uri: require("../assets/lithologies/728.jpg")},
	{key: 729, uri: require("../assets/lithologies/729.jpg")},
	{key: 730, uri: require("../assets/lithologies/730.jpg")},
	{key: 731, uri: require("../assets/lithologies/731.jpg")},
	{key: 732, uri: require("../assets/lithologies/732.jpg")},
	{key: 733, uri: require("../assets/lithologies/733.jpg")},
	{key: 998, uri: require("../assets/lithologies/998.jpg")},
	{key: 999, uri: require("../assets/lithologies/999.jpg")},
]

export const LITHOLOGIES_NAMES = {
	spanish: [
		{key: 601, name: "Grava o conglomerado (opción 1)"}, 
		{key: 602, name: "Grava o conglomerado (opción 2)"},
		{key: 603, name: "Conglometado o grava con estratificación cruzada"},
		{key: 605, name: "Brecha (opción 1)"},
		{key: 606, name: "Brecha (opción 2)"},
		{key: 607, name: "Arenisca o arena masiva"},
		{key: 608, name: "Arenisca o arena estratificada"},
		{key: 609, name: "Areniscas o arenas con estratificación cruzada (opción 1)"},
		{key: 610, name: "Areniscas o arenas con estratificación cruzada (opción 2)"},
		{key: 611, name: "Areniscas o arenas bandeadas y ripples"},
		{key: 612, name: "Areniscas lutíticas o arcillosas "},
		{key: 613, name: "Areniscas calcáreas"},
		{key: 614, name: "Areniscas dolomitas"},
		{key: 616, name: "Limo, limolita o limo arcilloso"},
		{key: 617, name: "Limolita calcárea"},
		{key: 618, name: "Limolita dolomítico"},
		{key: 619, name: "Lutita limosa o arenosa"},
		{key: 620, name: "Arcilla o lutita de arcilla"},
		{key: 621, name: "Lutitas con nódulos de cherts"},
		{key: 622, name: "Lutita dolomítica"},
		{key: 623, name: "Lutita calcárea o mármol"},
		{key: 624, name: "Lutita carbonosa"},
		{key: 625, name: "Lutita petrolífera"},
		{key: 626, name: "Caliza porosa (Chalk)"},
		{key: 627, name: "Caliza"},
		{key: 628, name: "Caliza clástica"},
		{key: 629, name: "Caliza clástica fosilífera"},
		{key: 630, name: "Caliza bandeada irregular o nodular"},
		{key: 631, name: "Caliza con Burrow rellenando caliza sacaraoidal"},
		{key: 632, name: "Caliza con estratificación cruzada"},
		{key: 633, name: "Caliza con estratificación cruzada y nódulos de cherts"},
		{key: 634, name: "Calizas clásticas con estratificación cruzada y nódulos de cherts"},
		{key: 635, name: "Caliza oolítica"},
		{key: 636, name: "Caliza arenosa"},
		{key: 637, name: "Caliza limosa"},
		{key: 638, name: "Caliza lutítica o arcillosa"},
		{key: 639, name: "Caliza con nódulos de cherts (opción 1)"},
		{key: 640, name: "Caliza con nódulos de cherts (opción 2)"},
		{key: 641, name: "Caliza dolomítica. Dolomía limosa"},
		{key: 642, name: "Dolomía"},
		{key: 643, name: "Dolomía con estratificación cruzada"},
		{key: 644, name: "Dolomía oolítica"},
		{key: 645, name: "Dolomía arenosa"},
		{key: 646, name: "Dolomía limosa"},
		{key: 647, name: "Dolomía lutítica o arcillosa"},
		{key: 648, name: "Dolomía con nódulos de cherts"},
		{key: 649, name: "Chert bandeado (opción 1)"},
		{key: 650, name: "Chert bandeado (opción 2)"},
		{key: 651, name: "Chert bandeado fosilífero"},
		{key: 652, name: "Roca fosilífera"},
		{key: 653, name: "Roca con diatomeas"},
		{key: 654, name: "Subgrauvaca"},
		{key: 655, name: "Subgrauvaca con estratificación cruzada"},
		{key: 656, name: "Subgrauvaca con ripples y bandeamiento"},
		{key: 657, name: "Turba"},
		{key: 658, name: "Carbón"},
		{key: 659, name: "Carbón con impurezas"},
		{key: 660, name: "Arcillas con restos de raíces"},
		{key: 661, name: "Arcillas con capas de carbón"},
		{key: 662, name: "Bentonita"},
		{key: 663, name: "Glauconita"},
		{key: 664, name: "Limonita"},
		{key: 665, name: "Siderita"},
		{key: 666, name: "Rocas con nódulos fosfáticos"},
		{key: 667, name: "Yeso"},
		{key: 668, name: "Sal"},
		{key: 669, name: "Areniscas interbandeadas"},
		{key: 670, name: "Areniscas y lutitas interbandeadas"},
		{key: 671, name: "Arenisca interbandeada con riples y caliza limosa"},
		{key: 672, name: "Lutita interbandeada y caliza limosa (dominancia lutítica)"},
		{key: 673, name: "Lutita interbandeada y caliza (dominancia lutítica) (opción 1)"},
		{key: 674, name: "Lutita interbandeada y caliza (dominancia lutítica) (opción 2)"},
		{key: 675, name: "Lutitas calcáreas y calizas (dominancia lutítica)"},
		{key: 676, name: "Caliza limosa interbandeada y lutita"},
		{key: 677, name: "Caliza interbandeada y lutita (opción 1)"},
		{key: 678, name: "Caliza interbandeada y lutita (opción 2)"},
		{key: 679, name: "Caliza interbandeada y lutita (caliza dominante)"},
		{key: 680, name: "Caliza interbandeada y lutita calcárea"},
		{key: 681, name: "Till (opción 1)"},
		{key: 682, name: "Till (opción 2)"},
		{key: 683, name: "Till (opción 3)"},
		{key: 684, name: "Loess (opción 1)"},
		{key: 685, name: "Loess (opción 2)"},
		{key: 686, name: "Loess (opción 3)"},
		{key: 701, name: "Metamorfismo"},
		{key: 702, name: "Cuarcita"},
		{key: 703, name: "Pizarra"},
		{key: 704, name: "Granito gneisico"},
		{key: 705, name: "Esquisto"},
		{key: 706, name: "Esquisto plegado"},
		{key: 707, name: "Esquisto y gneis"},
		{key: 708, name: "Gneis"},
		{key: 709, name: "Gneis plegado"},
		{key: 710, name: "Esteatita, talco o serpentina"},
		{key: 711, name: "Toba volcánica"},
		{key: 712, name: "Toba cristalina"},
		{key: 713, name: "Toba vítrea"},
		{key: 714, name: "Brecha volcánica y toba"},
		{key: 715, name: "Brecha volcánica o aglomerado"},
		{key: 716, name: "Zeolita"},
		{key: 717, name: "Flujo basáltico"},
		{key: 718, name: "Granito (opción 1)"},
		{key: 719, name: "Granito (opción 2)"},
		{key: 720, name: "Granito bandeado"},
		{key: 721, name: "Roca ígnea (opción 1)"},
		{key: 722, name: "Roca ígnea (opción 2)"},
		{key: 723, name: "Roca ígnea (opción 3)"},
		{key: 724, name: "Roca ígnea (opción 4)"},
		{key: 725, name: "Roca ígnea (opción 5)"},
		{key: 726, name: "Roca ígnea (opción 6)"},
		{key: 727, name: "Roca ígnea (opción 7)"},
		{key: 728, name: "Roca ígnea (opción 8)"},
		{key: 729, name: "Roca porfirítica (opción 1)"},
		{key: 730, name: "Roca porfirítica (opción 2)"},
		{key: 731, name: "Roca Vitrofídica"},
		{key: 732, name: "Cuarzo"},
		{key: 733, name: "Mena"},
		{key: 998, name: "Hiatus"},
		{key: 999, name: "Sin información"},
	],

	english: [
		{key: 601, name: "Gravel or conglomerate (1st option)"}, 
		{key: 602, name: "Gravel or conglomerate (2nd option)"},
		{key: 603, name: "Crossbedded gravel or conglomerate"},
		{key: 605, name: "Breccia (1st option)"},
		{key: 606, name: "Breccia (2nd option)"},
		{key: 607, name: "Massive sand or sandstone"},
		{key: 608, name: "Bedded sand or sandstone"},
		{key: 609, name: "Crossbedded sand or sandstone (1st option)"},
		{key: 610, name: "Crossbedded sand or sandstone (2nd option)"},
		{key: 611, name: "Ripple-bedded sand or sandstone"},
		{key: 612, name: "Argillaceous or shaly sandstone"},
		{key: 613, name: "Calcareous sandstone"},
		{key: 614, name: "Dolomitic sandstone"},
		{key: 616, name: "Silt, siltstone, or shaly silt"},
		{key: 617, name: "Calcareous siltstone"},
		{key: 618, name: "Dolomitic siltstone"},
		{key: 619, name: "Sandy or silty shale"},
		{key: 620, name: "Clay or clay shale"},
		{key: 621, name: "Cherty shale"},
		{key: 622, name: "Dolomitic shale"},
		{key: 623, name: "Calcareous shale or marl"},
		{key: 624, name: "Carbonaceous shale"},
		{key: 625, name: "Oil shale"},
		{key: 626, name: "Chalk"},
		{key: 627, name: "Limestone"},
		{key: 628, name: "Clastic limestone"},
		{key: 629, name: "Fossiliferous clastic limestone"},
		{key: 630, name: "Nodular or irregularly bedded limestone"},
		{key: 631, name: "Limestone, irregular (burrow?) fillings of saccharoidal dolomite"},
		{key: 632, name: "Crossbedded limestone"},
		{key: 633, name: "Cherty crossbedded limestone"},
		{key: 634, name: "Cherty and sandy crossbedded clastic limestone"},
		{key: 635, name: "Oolitic limestone"},
		{key: 636, name: "Sandy limestone"},
		{key: 637, name: "Silty limestone"},
		{key: 638, name: "Argillaceous or shaly limestone"},
		{key: 639, name: "Cherty limestone (1st option)"},
		{key: 640, name: "Cherty limestone (2nd option)"},
		{key: 641, name: "Dolomitic limestone, limy dolostone, or limy dolomite"},
		{key: 642, name: "Dolostone or dolomite"},
		{key: 643, name: "Crossbedded dolostone or dolomite"},
		{key: 644, name: "Oolitic dolostone or dolomite"},
		{key: 645, name: "Sandy dolostone or dolomite"},
		{key: 646, name: "Silty dolostone or dolomite"},
		{key: 647, name: "Argillaceous or shaly dolostone or dolomite"},
		{key: 648, name: "Cherty dolostone or dolomite"},
		{key: 649, name: "Bedded chert (1st option)"},
		{key: 650, name: "Bedded chert (2nd option)"},
		{key: 651, name: "Fossiliferous bedded chert"},
		{key: 652, name: "Fossiliferous rock"},
		{key: 653, name: "Diatomaceous rock"},
		{key: 654, name: "Subgraywacke"},
		{key: 655, name: "Crossbedded subgraywacke"},
		{key: 656, name: "Ripple-bedded subgraywacke"},
		{key: 657, name: "Peat"},
		{key: 658, name: "Coal"},
		{key: 659, name: "Bony coal or impure coal"},
		{key: 660, name: "Underclay"},
		{key: 661, name: "Flint clay"},
		{key: 662, name: "Bentonite"},
		{key: 663, name: "Glauconite"},
		{key: 664, name: "Limonite"},
		{key: 665, name: "Siderite"},
		{key: 666, name: "Phosphatic-nodular rock"},
		{key: 667, name: "Gypsum"},
		{key: 668, name: "Salt"},
		{key: 669, name: "Interbedded sandstone and siltstone"},
		{key: 670, name: "Interbedded sandstone and shale"},
		{key: 671, name: "Interbedded ripplebedded sandstone and shale"},
		{key: 672, name: "Interbedded shale and silty limestone (shale dominant)"},
		{key: 673, name: "Interbedded shale and limestone (shale dominant) (1st option)"},
		{key: 674, name: "Interbedded shale and limestone (shale dominant) (2nd option)"},
		{key: 675, name: "Interbedded calcareous shale and limestone (shale dominant)"},
		{key: 676, name: "Interbedded silty limestone and shale"},
		{key: 677, name: "Interbedded limestone and shale (1st option)"},
		{key: 678, name: "Interbedded limestone and shale (2nd option)"},
		{key: 679, name: "Interbedded limestone and shale (limestone dominant)"},
		{key: 680, name: "Interbedded limestone and calcareous shale"},
		{key: 681, name: "Till or diamicton (1st option)"},
		{key: 682, name: "Till or diamicton (2nd option)"},
		{key: 683, name: "Till or diamicton (3rd option)"},
		{key: 684, name: "Loess (1st option)"},
		{key: 685, name: "Loess (2nd option)"},
		{key: 686, name: "Loess (3rd option)"},
		{key: 701, name: "Metamorphism"},
		{key: 702, name: "Quartzite"},
		{key: 703, name: "Slate"},
		{key: 704, name: "Schistose or gneissoid granite"},
		{key: 705, name: "Schist"},
		{key: 706, name: "Contorted schist"},
		{key: 707, name: "Schist and gneiss"},
		{key: 708, name: "Gneis"},
		{key: 709, name: "Contorted gneiss"},
		{key: 710, name: "Soapstone, talc, or serpentinite"},
		{key: 711, name: "Tuffaceous rock"},
		{key: 712, name: "Crystal tuff"},
		{key: 713, name: "Devitrified tuff"},
		{key: 714, name: "Volcanic breccia and tuff"},
		{key: 715, name: "Volcanic breccia or agglomerate"},
		{key: 716, name: "Zeolitic rock"},
		{key: 717, name: "Basaltic flows"},
		{key: 718, name: "Granite (1st option)"},
		{key: 719, name: "Granite (2nd option)"},
		{key: 720, name: "Banded igneous rock"},
		{key: 721, name: "Igneous rock (1st option)"},
		{key: 722, name: "Igneous rock (2nd option)"},
		{key: 723, name: "Igneous rock (3rd option)"},
		{key: 724, name: "Igneous rock (4th option)"},
		{key: 725, name: "Igneous rock (5th option)"},
		{key: 726, name: "Igneous rock (6th option)"},
		{key: 727, name: "Igneous rock (7th option)"},
		{key: 728, name: "Igneous rock (8th option)"},
		{key: 729, name: "Porphyritic rock (1st option)"},
		{key: 730, name: "Porphyritic rock (2nd option)"},
		{key: 731, name: "Vitrophyre"},
		{key: 732, name: "Quartz"},
		{key: 733, name: "Ore"},
		{key: 998, name: "Hiatus"},
		{key: 999, name: "No information"},
	],
}