export const STRUCTURES_IMAGES = [
	{key: "a661", uri: require("../assets/structures/a661.png")},
	{key: "a662", uri: require("../assets/structures/a662.png")},
	{key: "a663", uri: require("../assets/structures/a663.png")}, 
	{key: "a664", uri: require("../assets/structures/a664.png")}, 
	{key: "a665", uri: require("../assets/structures/a665.png")}, 
	{key: "a666", uri: require("../assets/structures/a666.png")}, 
	{key: "a667", uri: require("../assets/structures/a667.png")}, 
	{key: "a668", uri: require("../assets/structures/a668.png")}, 
	{key: "a669", uri: require("../assets/structures/a669.png")}, 
	{key: "a6610", uri: require("../assets/structures/a6610.png")}, 
	{key: "a6611", uri: require("../assets/structures/a6611.png")},
	{key: "a6612", uri: require("../assets/structures/a6612.png")}, 
]

export const STRUCTURES_NAMES = {
	spanish: [
		{key: "a661", name: "Afilada, plana, paralela"},
		{key: "a662", name: "Afilada, irregular"},
		{key: "a663", name: "Lenticular o nodular"},
		{key: "a664", name: "Gradacional, irregular"},
		{key: "a665", name: "Corte transversal, no paralelo"},
		{key: "a666", name: "Caótica"},
		{key: "a667", name: "Cortina"},
		{key: "a668", name: "Recorrido o canal (lenticular)"},
		{key: "a669", name: "Ondulada"},
		{key: "a6610", name: "Tenue"},
		{key: "a6611", name: "Sigmoidal"},
		{key: "a6612", name: "Masiva"},
	],

	english: [
		{key: "a661", name: "Sharp, planar, parallel"},
		{key: "a662", name: "Sharp, irregular"},
		{key: "a663", name: "Lenticular or nodular"},
		{key: "a664", name: "Gradational, irregular"},
		{key: "a665", name: "Cross-cutting, non-parallel"},
		{key: "a666", name: "Chaotic"},
		{key: "a667", name: "Draping"},
		{key: "a668", name: "Scour or channel (lenticular)"},
		{key: "a669", name: "Wavy"},
		{key: "a6610", name: "Wispy"},
		{key: "a6611", name: "Sigmoidal"},
		{key: "a6612", name: "Massive"},	
	],
}